// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4xay-u3aox_CvIpJSNF7woWwLi3bVjlY',
    appId: '1:984740225939:android:610c533956029c8ae3be66',
    messagingSenderId: '984740225939',
    projectId: 'peeroreum-409506',
    storageBucket: 'peeroreum-409506.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIF_Z4E72oosJ73yg2U6u6tBrk3p8zZ8E',
    appId: '1:984740225939:ios:98facff641d2ee65e3be66',
    messagingSenderId: '984740225939',
    projectId: 'peeroreum-409506',
    storageBucket: 'peeroreum-409506.appspot.com',
    androidClientId: '984740225939-l27n8l5q2icrj1fudm4f3jhi479tm6tu.apps.googleusercontent.com',
    iosClientId: '984740225939-02sqnjvc9hr1lierr8mgrgrhph7cu8l9.apps.googleusercontent.com',
    iosBundleId: 'com.example.peeroreumClient',
  );
}
